### ISSUE TITLE
"--volumeup" or "--volumedown" parameters change system's volume instead of app's volume

### ISSUE THREAD

**Issue by jayypluss** [pwittchen/spotify-cli-linux#10]
It would be interesting if the "--volumeup" and "--volumedown" parameters altered only the app's volume, and not the system's volume.

**Comment by pwittchen** [comment]
Hi,

Thanks for reporting this issue. I'm not sure, if it's possible to control app volume, but I'll check it.

**Comment by maksimsdimov** [comment]
I have a PR waiting for this: https://github.com/pwittchen/spotify-cli-linux/pull/40

**Comment by pwittchen** [comment]
Fixed by @maksimsdimov in PR #40.
