### ISSUE TITLE
spotifycli: command not found

### ISSUE THREAD

**Issue by MemduhG** [pwittchen/spotify-cli-linux#20]
Hello, I've installed this using `pip install spotify-cli-linux`, and the pip installation looks like it went well: `Successfully installed spotify-cli-linux-1.0.0`. But when I try to run spotify cli it won't work.
```
$ spotifycli
spotifycli: command not found
```
What could be the issue here? I'm on Ubuntu 17.10 if that's any help.

**Comment by pwittchen** [comment]
It should work. Try to restart your terminal. If it won't help, uninstall app with `pip` and try to install again it using `curl` or `wget`.

**Comment by GrzegorzKlimek** [comment]
Had the same issue but installing via wget worked
