### ISSUE TITLE
use without spotify client 

### ISSUE THREAD

**Issue by mildfuzz** [pwittchen/spotify-cli-linux#21]
would  be great to be able to use this without the spotify client running, as I often have spotify running on a separate device

**Comment by pwittchen** [comment]
Thanks for the suggestion. It's nice idea. We can think of exposing this CLI program as a server with appropriate API (e.g. via separate project), so it could be controlled via clients from different devices over the local network or Internet.

**Comment by pwittchen** [comment]
I thinks this was somehow addressed in PR #45, where you can customize client. It is that ok for you @mildfuzz?

**Comment by pwittchen** [comment]
Ok, there's no response, so I'm closing it.
