### ISSUE TITLE
--volumeup or --volumedown does not nothing

### ISSUE THREAD

**Issue by samael205** [pwittchen/spotify-cli-linux#22]
Hi, i have installed spotify-cli-linux on arch linux,

all comands works fine to me except --volumeup && --volumedown. 

Is there any program in particular to control volume from cli?

Thanks

**Comment by pwittchen** [comment]
Hi,

It calls `pactl` under the hood. I'm not sure if it's an issue of the
hardware or particular distro. It works on my old (E550) and new (T470s)
ThinkPad laptops with the latest Ubuntu. Maybe  on Arch it should be done
in a different way.

Regards
Piotr

niedz., 1 lip 2018, 16:50 użytkownik Pedro Jose <notifications@github.com>
napisał:

**Comment by pwittchen** [comment]
There's no response in more than one month, so I assume it's resolved or outdated.
