### ISSUE TITLE
Feature request: Add song to playlist

### ISSUE THREAD

**Issue by OzQu** [pwittchen/spotify-cli-linux#23]
I usually add good songs from Discover Weekly -playlist to my Starred -playlist. It would be nice to use this cli application for that.

Example of the idea
`spotifycli --add-current-to-playlist starred --no-duplicates`

**Comment by pwittchen** [comment]
Thanks for the idea. It's really good. Nevertheless, we need to investigate if it's possible with this kind of API, which we're using in this app. AFAIK it's a bit limited.

**Comment by maksimsdimov** [comment]
This won't be possible with the current API. These are all the methods and properties exposed ATM:

`<interface name="org.mpris.MediaPlayer2.Player">
    <method name="Next"/>
    <method name="Previous"/>
    <method name="Pause"/>
    <method name="PlayPause"/>
    <method name="Stop"/>
    <method name="Play"/>
    <method name="Seek">
      <arg type="x" name="Offset" direction="in"/>
    </method>
    <method name="SetPosition">
      <arg type="o" name="TrackId" direction="in"/>
      <arg type="x" name="Position" direction="in"/>
    </method>
    <method name="OpenUri">
      <arg type="s" name="Uri" direction="in"/>
    </method>
    <signal name="Seeked">
      <arg type="x" name="Position"/>
    </signal>
    <property type="s" name="PlaybackStatus" access="read"/>
    <property type="s" name="LoopStatus" access="readwrite"/>
    <property type="d" name="Rate" access="readwrite"/>
    <property type="b" name="Shuffle" access="readwrite"/>
    <property type="a{sv}" name="Metadata" access="read"/>
    <property type="d" name="Volume" access="readwrite"/>
    <property type="x" name="Position" access="read"/>
    <property type="d" name="MinimumRate" access="read"/>
    <property type="d" name="MaximumRate" access="read"/>
    <property type="b" name="CanGoNext" access="read"/>
    <property type="b" name="CanGoPrevious" access="read"/>
    <property type="b" name="CanPlay" access="read"/>
    <property type="b" name="CanPause" access="read"/>
    <property type="b" name="CanSeek" access="read"/>
    <property type="b" name="CanControl" access="read"/>
  </interface>`

**Comment by pwittchen** [comment]
Ok, so I'm closing this for now. We can re-open this in the future, if it'll be feasible.
