### ISSUE TITLE
voidlinux Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.mpris.MediaPlayer2.spotify 

### ISSUE THREAD

**Issue by klapperys** [pwittchen/spotify-cli-linux#24]
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.mpris.MediaPlayer2.spotify was not provided by any .service files

voidlinux  dbus is installed using desktop client

any help would be appreciated thanks !

**Comment by pwittchen** [comment]
Try to install python-dbus package.

link: https://github.com/pwittchen/spotify-cli-linux#solving-problems

**Comment by klapperys** [comment]
python-dbus is installed and up to date

**Comment by pwittchen** [comment]
What Linux distribution are you using?
Do you have Spotify desktop client installed and running?

**Comment by klapperys** [comment]
my distro is voidlinux the client is running and working properly thanks !

**Comment by pwittchen** [comment]
Hm, it's hard to say what can be really wrong. It seems to be a distro issue because on more popular distros (like Ubuntu) everything works fine. Maybe this distro have different dbus implementation what makes this script incompatible with it or it's bugged on this distro (just guessing).
