### ISSUE TITLE
Give shell-like capabilities

### ISSUE THREAD

**Issue by kindlehl** [pwittchen/spotify-cli-linux#34]
This tool would be so much nicer if there was an option to act as a shell. Its tiring to type spotify --<command> and going thru history to find a spotify commands and changing them, etc. It would be much nicer if the program, when ran without arguments, turned into a shell. You could then pass the shell commands which would invoke the regular program with the -- parameters or otherwise use the internal functions.

**Comment by pwittchen** [comment]
It's being implemented in PR #35.

**Comment by pwittchen** [comment]
Done.
