### ISSUE TITLE
Change volume step by way of config rather than hard-code

### ISSUE THREAD

**Issue by boardfish** [pwittchen/spotify-cli-linux#4]
Quite tempted to contribute on this one myself, but in the [most recent commit](https://github.com/pwittchen/spotify-cli-linux/commit/97d875458428fee3857cba01ad1d4f27779a2eef) as of this post, the volume steps are hardcoded at 5%. Could the user define this themselves?

**Comment by pwittchen** [comment]
Yes, it can be updated and we can make it configurable.

16.05.2017 2:58 PM "Simon Fish" <notifications@github.com> napisał(a):

**Comment by boardfish** [comment]
Wow, it's been maybe a year and a half since my original comment. At that time, I didn't really have PRs and contribution to public repos down. Happy to take this one up again, and I mean it this time!

**Comment by pwittchen** [comment]
Sure. PRs and comments are welcome. :-)

pon., 5 lis 2018, 14:15: Simon Fish <notifications@github.com> napisał(a):

**Comment by pwittchen** [comment]
I removed volume support due to strange OS issues.
