### ISSUE TITLE
key error 'spotifyClidentID'

### ISSUE THREAD

**Issue by shiasyn** [pwittchen/spotify-cli-linux#42]
Sorry, I probably cannot do more than raising an issue, cuz I couldn't even get application up and running by now

but I've found a couple of details that might help someone in the future: 
so the first is about dependencies: it's lyricswikia and spotipy, so for me the installation command was ``` sudo pip install lyricswikia spotipy spotifycli ```

second is about the name of the application, when I try ```spotifycli``` I get command not found, because the actual command name is ```SpotifyCLI```

and third is that it seems that file /usr/bin/SpotifyCLI has 
``` #!/usr/local/opt/python/bin/python3.7 ```
which seems like a path for a homebrew python installation
I guess the output of  ```$ which python ``` should be there
because on linux it is most likely ```/usr/bin/python``` (which in my case is)

now I'm stuck with ```KeyError 'SpotifyClientID``` :(

my distro is manjaro with zsh

**Comment by pwittchen** [comment]
Hi,

Thanks for reporting this. I think this issue may be related to other tool than `spotifycli` or other tool is in conflict (e.g. name conflict) with it. `spotifycli` uses `lyricwikia` for getting lyrics (I don't know why pip doesn't resolve that as it's defined in setup.py). Nevertheless `spotipy` is **not** on the dependency list for this project. The actual command for this project is **not** `SpotifyCLI`. It's not defined anywhere as a variable or file name. It's `spotifycli`. I'm also **not using** any variable like `SpotifyClientID`. The error you provided comes from another tool (maybe `spotipy`?).

**Comment by shiasyn** [comment]
@pwittchen Thanks for the reply! I guess I'll try to find and remove all stuff that I've tried to use to controll spotify via cli and try from scratch :)
