### ISSUE TITLE
lyricwikia dependency not being fetched 

### ISSUE THREAD

**Issue by z3t0** [pwittchen/spotify-cli-linux#43]
https://github.com/pwittchen/spotify-cli-linux/blob/d72490be4023de5d197aa64787edeb874f8a02d9/setup.py#L18

I noticed #41 documents this issue, was wondering if you had any thoughts on why lyricwikia was not being fetched as a dependency?

**Comment by pwittchen** [comment]
I don't know why it's not fetched. I thought, this definition is enough.

**Comment by z3t0** [comment]
I think the install_require needs to be renamed to packages.

I'll do a test and get back to you.

**Comment by pwittchen** [comment]
Ok

--
Piotr Wittchen,
http://wittchen.io

pon., 22 kwi 2019, 15:17 użytkownik Rafi Khan <notifications@github.com>
napisał:

**Comment by pwittchen** [comment]
I had this problem before, but after fresh OS install with new distro, it doesn't occur anymore. I think, it may be related to some mess connected with pip, different python versions, specific system setup, etc. - not the library itself. I think, it can be closed.

**Comment by alexfornuto** [comment]
For others brought here by google, I solved by using `pip3` instead of `pip`.
