### ISSUE TITLE
Play Playlist URI - feature request 

### ISSUE THREAD

**Issue by feirsom** [pwittchen/spotify-cli-linux#5]
Are you willing to create a feature to play a specified playlist instead of just one particular song? Or is this already possible with existing commands? Thanks!

**Comment by feirsom** [comment]
Also, is it possible to have a command that toggles the repeat/shuffle settings to true?

**Comment by pwittchen** [comment]
Right now, this tool allows you to play/pause a current song or play next/prev song on the existing playlist. I quickly checked Spotify API and I think it should be possible to play a playlist from the specified URI. 

I'm not sure about repeat/shuffle feature. For now, it'll behave as the user set it in desktop Spotify app.
