### ISSUE TITLE
Spotify is off

### ISSUE THREAD

**Issue by VijayrajS** [pwittchen/spotify-cli-linux#50]
I installed the cli and dbus using pip; python version 3.6.8. If I try any cmmand, I get the following error:
```dbus[]: Dynamic session lookup supported but failed: launchd did not provide a socket path, verify that org.freedesktop.dbus-session.plist is loaded!  Spotify is off```

**Comment by pwittchen** [comment]
Have you turned the Spotify desktop app on? It's required for this program. What linux distro are you using? Moreover, check this section https://github.com/pwittchen/spotify-cli-linux#solving-problems.

**Comment by VijayrajS** [comment]
I'm on macOS Mojave (10.14.5), and yes, my Spotify Desktop was on.

**Comment by pwittchen** [comment]
Ok, as the app name says, it's spotify-cli-linux. It doesn't work on macOS.
It's dedicated for Linux only.

--
Piotr Wittchen,
http://wittchen.io

sob., 6 lip 2019, 10:14 użytkownik Vijayraj Shanmugaraj <
notifications@github.com> napisał:

**Comment by VijayrajS** [comment]
Oh, I'm sorry

**Comment by pwittchen** [comment]
You can try to use shpotify app linked in the README. It works on macOS.

--
Piotr Wittchen,
http://wittchen.io

sob., 6 lip 2019, 10:51 użytkownik Vijayraj Shanmugaraj <
notifications@github.com> napisał:

**Comment by c00degrammer** [comment]
hey!
i have same problem on UBUNTU.
https://i.imgur.com/NHhBZjQ.png

**Comment by pwittchen** [comment]
It's strange. I haven't seen that issue on linux before.

**Comment by c00degrammer** [comment]
fixed auto after reboot :)
but cant find lyrics.
https://i.imgur.com/CB4cpN4.png
