### ISSUE TITLE
Feature request: display play or pause status

### ISSUE THREAD

**Issue by plivxo** [pwittchen/spotify-cli-linux#6]
Feature request:
It would be nice with an option like "--showplaystatus" which whould output either "playing" or "paused" or "stopped" or similar. My use case is this: I have a key on my keyboard which I have bound to a script which I like to stop any music player that's currently playing - it can be Spotify, but it could be other music players as well. Since I don't know if Spotify is playing, I cannot use the --playpause option.
  Today, you have  a --status option, but it displays the same output whether the song is playing or paused.
Thanks in advance! :-)

**Comment by sflip** [comment]
I added a `--stop` option [in my fork](https://github.com/sflip/spotify-cli-linux).

**Comment by pwittchen** [comment]
Done in #26.
