### ISSUE TITLE
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.mpris.MediaPlayer2.spotify was not provided by any .service files

### ISSUE THREAD

**Issue by chubin** [pwittchen/spotify-cli-linux#7]
```
$ python spotify-cli --next
Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.mpris.MediaPlayer2.spotify was not provided by any .service files
```

Do I need something else have installed/configured to run it?

**Comment by pwittchen** [comment]
Hi,

See this section https://github.com/pwittchen/spotify-cli-linux#solving-problems

In addtion, please remember it works only on Linux.

**Comment by chubin** [comment]
Obviously I have, and when I'm using it in browser everything works fine.
But if I try to use the tool, I get this error message

**Comment by pwittchen** [comment]
>  I'm using it in browser
This tool works with a desktop app - not with the web browser app. Please, try to install and open desktop Spotify app and then try the script.

**Comment by chubin** [comment]
That is the problem I think. Ok, I need to try it. I close the issue
