### ISSUE TITLE
User info / login credentials for paid account?

### ISSUE THREAD

**Issue by sweddle** [pwittchen/spotify-cli-linux#8]
Hi the app looks nice and simple. but how do we enter our Spotify credentials? Thanks

**Comment by pwittchen** [comment]
You don't need to enter them. It uses an instance of the Linux desktop
Spotify app, which should be installed and running. Once you're logged into
the desktop app (as free or premium user), you don't need to login again
with this script.

29.12.2017 8:34 PM "sweddle" <notifications@github.com> napisał(a):

**Comment by pwittchen** [comment]
There are no further responses, so I'm closing it.
