### ISSUE TITLE
Issue at README.md

### ISSUE THREAD

**Issue by G1A1B1E** [pwittchen/spotify-cli-linux#81]
On install section in readme there is an issue.

**WRONG:** `git clone git@github.com:pwittchen/spotify-cli-linux.git `
it tries to ssh into the repo.

**FIX:** `git clone https://github.com/pwittchen/spotify-cli-linux`
this actually clones the repo instead.

**Comment by pwittchen** [comment]
Both options should work. Second option would be fine, if you don't plan to commit and push to this repo and just have it in read-only mode.

**Comment by pwittchen** [comment]
Maybe you don't have configured git locally with ssh keys.

**Comment by G1A1B1E** [comment]
Your probably right
