### ISSUE TITLE
Fails in snap-installed Pycharm

### ISSUE THREAD

**Issue by Myoldmopar** [pwittchen/spotify-cli-linux#84]
First, thank you for this little library, it's really convenient.

I was going to build a little workflow around Spotify for my personal use, and your library looked appealing.  I created a fresh project in PyCharm, listed your library as a dependency and it installed nicely.  I tried `spotifycli --song` from the embedded terminal and hit an unhandled exception:

```
Traceback (most recent call last):
  File ".venv/bin/spotifycli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File ".venv/lib/python3.12/site-packages/spotifycli/spotifycli.py", line 34, in main
    show_song()
  File ".venv/lib/python3.12/site-packages/spotifycli/spotifycli.py", line 164, in show_song
    _, title = get_song()
               ^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/spotifycli/spotifycli.py", line 120, in get_song
    artist = ", ".join(metadata['xesam:artist'][1])
                       ~~~~~~~~^^^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
```

This seemed odd, so I made a quick script to call into your library and step through with a debugger, and found my way into `get_spotify_property`.  When I got to the end of the function after the dbus call, the `body` variable held this informational message:

> An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.523" (uid=1000 pid=416872 comm=".venv/b" label="snap.pycharm-professional.pycharm-professional (complain)") interface="org.freedesktop.DBus.Properties" member="Get" error name="(unset)" requested_reply="0" destination="org.mpris.MediaPlayer2.spotify" (uid=1000 pid=411197 comm="/snap/spotify/81/usr/share/spotify/spotify" label="snap.spotify.spotify (enforce)")

My PyCharm is snap installed, so I immediately jumped out of the PyCharm terminal and tried running `spotifycli --song` in a standalone terminal and it works fine.  This issue is simply because the PyCharm snap install is locked down via AppArmor.  

I'm not suggesting you need to do anything about this situation.  I'm just wanting to put this as an issue for others to find if they encounter this. 

If anything maybe add a bit of error handling at the spot I hit the unhandled exception to check invalid data before attempting to parse `xesam:artist`?  Or maybe there is a way to check the dbus response to see if AppArmor was blocking the communication?

Thanks for this nice little library, have a great day!

**Comment by pwittchen** [comment]
Thanks for reporting this issue. If you or anyone else wants to fix it, I'm open for the PRs.
