### ISSUE TITLE
"--status" parameter not showing full name of the song

### ISSUE THREAD

**Issue by Jonathanfk1** [pwittchen/spotify-cli-linux#9]
![image](https://user-images.githubusercontent.com/17395606/34606129-4ebe1c92-f1f5-11e7-94de-f4e7fc5a00ca.png)

**Comment by pwittchen** [comment]
Hi,

Thanks for reporting this issue. It's done on purpose. I'm using this script in my tmux plugin (https://github.com/pwittchen/tmux-plugin-spotify) and shortening names saves some space on the bottom bar.

Nevertheless, we can think of the following options:
- `--status-short` (like `--status` now)
- `--status` (full name)

It would be more flexible.

**Comment by pwittchen** [comment]
Fixed in PR #11.
